### DISCUSSION TITLE
Custom Favicon in the Browser's Title Bar

### DISCUSSION THREAD

**Discussion by ghost** [imfing/hextra#21] [Q&A] [answered]
I'm trying to change the icon in the browser's title bar, but unable to do so.

I have the below files in the `static/` directory:

```
static
├── android-chrome-512x512.png
├── apple-touch-icon.png
├── favicon.ico
├── favicon.png
├── favicon.svg
└── robots.txt
```

and `hugo.yaml` contains:

```yaml
params:
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: favicon.svg
      dark: favicon.svg
```

How can I ensure that a custom icon gets displayed in the browser's title bar?
