### DISCUSSION TITLE
One Hextra theme with two projects under same domain name

### DISCUSSION THREAD

**Discussion by fmunteanu** [imfing/hextra#396] [Q&A]
I have [my website](https://github.com/axivo/website) deployed with Github Pages, using Hextra. My goal is to combine the content of `./docs` and `/k3s-cluster` into `./docs/public`. The output is totally different, because each `hugo.yaml` has settings that cannot be combined. For example, the `menu.main` is different in each `hugo.yaml` configuration file. Ideally, I would like to use a global `hugo.yaml`, and in each directory to have just the customized settings.

Running the following commands does not generates the content in  `./docs/public/k3s-cluster`, I'm not sure what am I missing:

```
hugo --gc --minify -s ./docs
Start building sites …
hugo v0.125.7+extended darwin/arm64 BuildDate=2024-05-08T14:46:24Z VendorInfo=brew
                   | EN
-------------------+-----
  Pages            |  8
  Paginator pages  |  0
  Non-page files   |  0
  Static files     | 13
  Processed images |  0
  Aliases          |  0
  Cleaned          |  0

hugo --gc --minify -s ./k3s-cluster -d ./docs/public/k3s-cluster
Start building sites …
hugo v0.125.7+extended darwin/arm64 BuildDate=2024-05-08T14:46:24Z VendorInfo=brew
                   | EN
-------------------+-----
  Pages            | 53
  Paginator pages  |  0
  Non-page files   |  5
  Static files     | 15
  Processed images |  0
  Aliases          |  0
  Cleaned          |  0
```

**Comment by fmunteanu** [comment]
I found a solution, but IMO is not a perfect one. Example of [website](https://axivo.com), combining two projects. Looking at [hugo.yml](https://github.com/axivo/website/blob/main/.github/workflows/hugo.yml) workflow, there are 2 execution steps:

```yaml
      - name: Build Content
        env:
          HUGO_ENV: production
          HUGO_ENVIRONMENT: production
          TZ: America/New_York
        run: |
          hugo --gc --minify -s ./docs
          hugo --gc --minify -s ./k3s-cluster -d "$(pwd)/docs/public/k3s-cluster"
```

The key is to add the full path, otherwise the `--source` will predefine where the destination will be.

My goal is to use one Hextra module, then define two `/docs` and `/k3s-cluster` directories where customized details are defined for each specific deployment. This way, I end-up with only one 404, for example.
