### DISCUSSION TITLE
authors as taxonomies?

### DISCUSSION THREAD

**Discussion by xuanswe** [imfing/hextra#606] [Q&A]
I follow https://moonbooth.com/hugo/authors/ to create taxonomy authors.

```
taxonomies:
  author: 'authors'
  tag: 'tags'
```

Then front matter needs to be like this:
```
authors:
  - author1
  - author2
tags:
  - tag1
  - tag2
```

Now, http://localhost:1313/authors/ and http://localhost:1313/tags/ should list all terms correctly.

---

But Hextra requires a different format for authors because it needs link and image.
```
authors:
  - name: imfing
    link: https://github.com/imfing
    image: https://github.com/imfing.png
  - name: Octocat
    link: https://github.com/octocat
    image: https://github.com/octocat.png
```

---

My 1st question is, how to make http://localhost:1313/authors/ working nicely together with Hextra authors?

My 2nd question:
Let's say if it works, another thing to consider is that, we want to have 2 actions when click on an author: open the link of the author (ex. https://github.com/imfing) and open a list page to list all pages of the author (ex. http://localhost:1313/authors/). Maybe the solution is that:
* click on the text => open list page with all author's pages, ex. http://localhost:1313/authors/
* open on the external link icon => open the author's link, ex. https://github.com/imfing
