### DISCUSSION TITLE
How can I have nested main menu?

### DISCUSSION THREAD

**Discussion by xuanswe** [imfing/hextra#625] [Q&A] [answered]
Hi, is it possible to create a menu item that has a dropdown icon?
For example, when clicking on the root menu item "Posts", it opens the "Posts" page. When clicking on the dropdown icon, it shows children menu items.

I tried this, but the theme ignores the "New Post" menu item.

```
menus:
  main:
    - weight: 1
      identifier: 'posts'
      name: 'Posts'
      pageRef: '/posts'
    - weight: 2
      identifier: 'new-post'
      name: 'New Post'
      parent: 'posts'
      url: '/admin/#/collections/posts/new'
```
