### ISSUE TITLE
Footer is enabled in config but not displayed

### ISSUE THREAD

**Issue by mfaure** [imfing/hextra#205]
**Description**

Footer is enabled in config but not displayed

**Steps To Reproduce**

1. Have a Hugo site with theme Hextra
2. In `config.toml`, add
  ```toml
  [footer]
  enable = true
  displayCopyright = true
  displayPoweredBy = true
  width = "normal"
  ```
3. Create `i18n/en.yaml` and add a special unique word as footer text: 
  ```yaml
  ---
  copyright: "© HoubAsqatasun"
  ```
4. Rebuild

**Expected Behavior**

We should see the word `HoubAsqatasun` in the footer.

**Actual Behavior**

Footer only displays `Powered by Hextra`

**Screenshots**

![image](https://github.com/imfing/hextra/assets/1173014/6e300aaf-99c6-48fc-b972-0956d9484d38)

**Environment**

- Hugo Version: 0.119.0
- Browser/OS: Firefox Nightly (same behaviour on Chrome)
- Theme Version: 0.6.5

**Additional Context**

* [Our merge request, on our repos, to customize the footer](https://gitlab.com/asqatasun/asqatasun-documentation-v6/-/merge_requests/13/diffs)

/cc @imfing

**Comment by imfing** [comment]
thanks for reporting, will look into this

**Comment by imfing** [comment]
> @mfaure I think you should use instead: `poweredBy: ""` for my part it works even if I cannot delete the logo but I think that with custom css it should do it
> 
> 
> 
> ![powershell_JE4aL6g6rF](https://github.com/imfing/hextra/assets/95414249/0e3ffa44-7a5b-494d-8d35-88339c4d7208)
> 
> 

I'll fix it by the end of the week.

**Comment by imfing** [comment]
@mfaure I think the main reason why the config didn't take effect was that the configuration field was wrong. The `footer` field should be put under `params`.

```toml
[params.footer]
enable = true
displayCopyright = true
displayPoweredBy = true
```
