### ISSUE TITLE
dark logo is not working

### ISSUE THREAD

**Issue by trieska** [imfing/hextra#232]
I think that following line in `layouts/partials/navbar.html` 

    {{- $logoDarkPath := .Site.Params.navbar.logo.dark | default $logoPath -}}

should be like this

    {{- $logoDarkPath := .Site.Params.navbar.logo.dark | default "images/logo-dark.svg" -}}

**Comment by imfing** [comment]
Hi, may i ask how did you configure the dark logo?

**Comment by trieska** [comment]
I did put logo.svg and logo-dark.svg to `static/images`

light version is working ok but dark one not

**Comment by imfing** [comment]
can you help provide an example minimal repository that reproduce this issue?

**Comment by librehugohu** [comment]
My [repos](https://github.com/librehugohu/librehugohu.github.io) has the same problem.

**Comment by trieska** [comment]
sorry for late response

I did solve this by renaming logo file to `bm.svg` and `bm-dark.svg` and update configuration

    params:
      navbar:
        displayTitle: true
        displayLogo: true
        logo:
          path: images/bm.svg
          dark: images/bm-dark.svg
          width: 50
          height: 50

**Comment by librehugohu** [comment]
> @librehugohu thanks for providing your repo as an example. I'll have a look at it. 

I tried the solution above, and it worked now.

**Comment by imfing** [comment]
I still couldn't reproduce this on my instance. 

```
params:
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/logo.svg
      dark: images/logo-dark.svg
      link: /
      width: 40
      height: 20
```
![image](https://github.com/imfing/hextra/assets/5097752/110871d2-f98b-4130-8da0-af49f4191ef7)
