### ISSUE TITLE
KaTeX  Environment Support

### ISSUE THREAD

**Issue by cas-liszinski** [imfing/hextra#528]
Does these environments are supported?

https://katex.org/docs/supported.html#environments

Is next syntax incorrect?

```tex
\begin{matrix}
   a & b \\
   c & d
\end{matrix}
```

**Comment by imfing** [comment]
Hi @cas-liszinski it should work. 

I found that with the default setting the newline separator `\\` needs to be explicitly escaped to `\\\\` for the matrix rows to show on separate lines.

To fix this, you need to configure in the `hugo.yaml` to enable [passthrough for math block](https://gohugo.io/content-management/mathematics/#step-1):
```
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
```

and the katex block should work perfectly:

<img src="https://github.com/user-attachments/assets/5777e552-2e9f-4a39-898f-d270002776cb" width=400></img>

<img src="https://github.com/user-attachments/assets/9f733e22-efc0-4672-b42c-182217be0906" width=400></img>

I will update the documentation to include this instruction. Thanks for bringing it up!
