### ISSUE TITLE
Sidebar "more" menu wrong URL with multilingual + GH hosting

### ISSUE THREAD

**Issue by patdavid** [imfing/hextra#593]
**Description**

Adding a menu item to the sidebar menu works fine in the default lang:

```
menu:
  sidebar:
    - identifier: more
      name: More
      params:
        type: separator
      weight: 1
    - identifier: about
      name: About
      pageRef: /how-to-contribute
      weight: 2
```

Deploying to GH pages ([from the docs](https://github.com/imfing/hextra-starter-template/blob/main/.github/workflows/pages.yaml#L60)) where it's of the form: `https://<USERNAME>.github.io/<REPO>/`

If there's another language the sidebar menu will use a URL of the form `<LANG>/<REPO>/<page>` when it should be `<REPO>/<LANG>/<page>`.  Note that the other links in the sidebar that are actually ok.

This is actually happening on the Hextra GH hosted site.
Go to the "Deploy Site" page for example.
https://imfing.github.io/hextra/docs/guide/deploy-site/

Check the sidebar for a link to "About" and see the link URL:

![Image](https://github.com/user-attachments/assets/6e6b5e18-b0e2-45c6-8db1-fb1b82ae4dc9)

Then change the language to one of the others, like japanese and check the same link (About) URL:

![Image](https://github.com/user-attachments/assets/56bf1d35-97e3-4a36-a008-2bdc55a41cff)

The link is `https://imfing.github.io/ja/hextra/about/`
When it _should_ be: `https://imfing.github.io/hextra/ja/about/`
