### ISSUE TITLE
Add directory layout

### ISSUE THREAD

**Issue by simchev** [imfing/hextra#645]
**Feature Description**

The idea is to be able to document a directory structure, whether it's an OS directory, or any kind of deeply nested tree structure.

**Problem/Solution**

The basic nav bar starts to get messy at depths of 4+. If you need to document any deeply nested structure, it gets really hard to navigate.

I propose we add a new layout type of "tree" or "directory", which would be a specific kind of /docs where we show a navigable tree at the top, and it shows the content based on your navigation in that tree. 

**Alternatives Considered**

No satisfying alternatives other than splitting, but it defeats the purpose.

**Comment by imfing** [comment]
@simchev hey, can you show me some examples? 

personally, I think sidebar navigation isn’t ideal for deeply nested structures (like the 4+ you mentioned). That said, you could implement a custom "tree" shortcode or template and embed it into the theme where needed. That might be a more flexible approach than wait for a theme level solution from my end.

**Comment by dbowling** [comment]
I add the following in `src/assets/css/custom.css` to address this problem. It's not 100% scalable, but it turned our Hextra documentation into something workable with 5 layers deep. 

We make use of the top navigation for major sections, then hide non-active sections in the sidebar. For really deep pages, we reduce the font size some (this doesn't look great, but it is a compromise that is worth it for us.)

```css
/* Shrink deeply nested navigation links */
body > div > aside > div > ul > li.open > div > ul > li.open > div > ul > li.open > div > ul > li  a {
    font-size: .7rem;
    padding: 0;
}

/* Hide non-opened sidebar navigation (in favor of top-nav) */
body > div > aside > div > ul > :not(li.open) {
    display: none;
}
```
